version: '3.4'

services:
  
  demo.service.widgets:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Data Source=tcp:db;Initial Catalog=Widgets;User Id=sa;Password=Password123;persist security info=False;packet size=4096
      - SeqUrl=http://logs
    ports:
      - "5002:80"   
      
  logs:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5010:80"
      
  db:
    environment:
      - SA_PASSWORD=Password123*
      - ACCEPT_EULA=Y
    ports:
      - "51433:1433"
